//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudioPlayerWCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audio
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public Nullable<int> Performer { get; set; }
        public string Path { get; set; }
        public Nullable<int> Duration { get; set; }
    
        public virtual Performer Performer1 { get; set; }
    }
}
